# This file tells Render how to build and run your services.

services:
  # 1. The Rails API Web Service
  - type: web
    name: openmat-api
    runtime: ruby
    plan: free


    buildCommand: "./bin/render-build.sh"

    # How to start the app
    startCommand: "bundle exec puma -C config/puma.rb"

    # Environment variables
    envVars:
      - key: RAILS_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: openmat-db # Must match the 'name' in the 'databases' block
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

databases:
  # 2. The PostgreSQL Database
  - name: openmat-db
    plan: free
    databaseName: openmat_production
    user: openmat_user
    postgresMajorVersion: 14